- name: Enable Gluster yum repository
  yum:
    name: centos-release-gluster
    state: present

- name: Install python3-pyxattr (glusterfs dependency)
  dnf:
    name: python3-pyxattr
    enablerepo: PowerTools

- name: Install glusterfs-server package
  yum:
    name: glusterfs-server-7.4-1.el8
    state: present

- name: Start glusterfs server
  service:
    name: glusterd
    state: started

- name: Probe glusterfs nodes
  run_once: true
  gluster_peer:
    state: present
    nodes: "{{ play_hosts }}"