---
- hosts: all
  remote_user: rancher
  become: yes
  roles:
    #- { role: ../ansible-role-swarm }
    #- { role: ../ansible-role-macvlan }
    - { role: ../ansible-role-dns, cnt_uid: 2001, cnt_gid: 2001 }
    #- { role: ../homecentr-monitoring } # Grafana, Prometheus etc.