- include_tasks: iam.yml

- name: Create Prometheus Docker config
  run_once: true
  docker_config:
    name: homecentr-prometheus
    data: "{{ lookup('template', 'prometheus.yml.j2') | b64encode }}"
    data_is_b64: true
    state: present

- name: Monitoring stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-monitoring
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"