- include_tasks: iam.yml

- name: Create Prometheus Docker config
  run_once: true
  template:
    src: prometheus.yml.j2
    dest: /tmp/prometheus.yml

- name: Monitoring stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-monitoring
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"

- name: Remove temporary config file
  run_once: true
  file:
    path: /tmp/prometheus.yml
    state: absent  