version: "2.4" # Version 2 is used because 3 does not support full ipam config (e.g. ip_range)
networks:
  macvlan:
    name: homecentr-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"
          ip_range: "192.168.2.32/28"