version: "3.7"
networks:
  macvlan:
    name: homecentr-macvlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"
          ip_range: "192.168.2.48/28"