- name: Named.conf
  run_once: true
  template:
    src: "{{ role_path }}/templates/named.conf.{{ dns_mode }}.j2"
    dest: "{{ volumes_root }}/homecentr-dns/config/named.conf"
    owner: "{{ cnt_uid }}"
    group: "{{ cnt_gid }}"
    mode: '0640'
    force: yes
  notify: restart_master

- name: Root zone
  run_once: true
  template:
    src: "{{ role_path }}/templates/root.zone.master.j2"
    dest: "{{ volumes_root }}/homecentr-dns/config/root.zone"
    owner: "{{ cnt_uid }}"
    group: "{{ cnt_gid }}"
    mode: '0640'
    force: yes
  notify: restart_master

- name: Servers reverse zone
  run_once: true
  template:
    src: "{{ role_path }}/templates/root.zone.master.j2"
    dest: "{{ volumes_root }}/homecentr-dns/config/servers_reverse.zone"
    owner: "{{ cnt_uid }}"
    group: "{{ cnt_gid }}"
    mode: '0640'
    force: yes
  notify: restart