- name: Create group dns
  group:
    name: dns
    gid: "{{ cnt_gid }}"
    state: present

- name: Create user dns
  user:
    name: dns
    uid: "{{ cnt_uid }}"
    group: dns
    groups:
      - dns
    state: present