galaxy_info:
  role_name: monitoring
  author: Lukas Holota
  description: Sets up the Prometheus/Grafana based monitoring Docker swarm stack
  company: HomeCentr

  license: MIT

  min_ansible_version: 2.7

  galaxy_tags:
    - Docker
    - Swarm
    - HomeCentr

dependencies:
  - homecentr.swarm