galaxy_info:
  role_name: dns
  author: Lukas Holota
  description: Sets up NGINX based reverse proxy for other globally deployed service
  company: HomeCentr

  license: MIT

  min_ansible_version: 2.7

  galaxy_tags:
    - Docker
    - Swarm
    - HomeCentr

dependencies:
  - homecentr.pip